name: Continuous Integration

on: 
  pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Using node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x

      - name: run install
        run: | 
          npm install
