name: Continuos Integration

on: 
  pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v2
        with: 
          node-vesion: 16.x
      - name: run install
        run: | 
          npm install
